import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Home, AlarmClock, FishSymbol, Wrench } from "lucide-react";
import { SidebarDesktop } from "@/components/sidebar-desktop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>

        <SidebarDesktop sidebarItems={{

          links: [
            {
              label: "Dashboard",
              href: "/",
              icon: Home,
            },
            {
              label: "Jadwal",
              href: "/jadwal",
              icon: AlarmClock,
            },
            {
              label: "Pakan",
              href: "/pakan",
              icon: FishSymbol,
            },
            {
              label: "Alat",
              href: "/alat",
              icon: Wrench,
            },
          ],
        }} />

        <main className='ml-[300px] mt-3'>{children}</main>
      </body>
    </html>
  );
}
